### PR TITLE
Solving "Navigation Bar of web client is not responsive" issue #221

### LINKED ISSUE #221: Navigation Bar of web client is not responsive
# Expected Behavior
Navigation Bar of web client should be mobile responsive

# Current Behavior
Navigation Bar is NOT responsive

Screen Shot 2019-03-22 at 11 03 54 AM

# Failure Information (for bugs)
## Steps to Reproduce
- Decreasing the window size of the browser

### PR DESCRIPTION
**Pull request by wdevon99**
The navigation bar was not responsive so I fixed the issued by implementing a custom nav bar with a side drawer. 

**Test plan (required)**
Screenshots of new improved nav bar!
Screen Shot 2019-03-22 at 7 23 15 PM
Screen Shot 2019-03-22 at 7 31 59 PM
Screen Shot 2019-03-22 at 7 22 34 PM

**Code formatting**

**Closing issues**
closes #221

### CODE REVIEW

**Comment by wdevon99** [comment]
@ivantha @root5533  Please review when you are free and let me know if anything needs to be changed

**Comment by root5533** [comment]
There are merge conflicts please resolve them

**Comment by wdevon99** [comment]
> @wdevon99 Please rebase

Sure willl do this asap!

**Comment by wdevon99** [comment]
> @wdevon99 Please rebase

Done!

**Pull request closed without merging**
