### PR TITLE
requirements.txt updated

### PR DESCRIPTION
**Pull request by alankritgupta091099**
urllib3 rollbacked to v1.22 as previously it was unstable.
My Machine config.- Ubuntu 18.04, Python 3.6.9

### CODE REVIEW

**Comment by root5533** [comment]
What does this PR accomplish ? It is unclear from your description and there are no file changes from this PR.

**Comment by alankritgupta091099** [comment]
With the earlier version of urllib3, the elastic search was not able to install due to incompatibility issues. Therefore I rollbacked it to the compatible version.

**Comment by root5533** [comment]
Ok so what file have you changed ? The commits you have submitted is regarding a slider and then reverted back. There is nothing to commit here. Please check again whether the changes you need is happened here.

**Comment by alankritgupta091099** [comment]
For this, I changed the version of urllib3 in 'requirements.txt' file in 'fact-bounty-flask' folder. The commit which I made with message "slider added to navbar" was not related to this urllib3. It was done by mistake that is why I reverted it back. "slider added to navbar" commit is for toggling dark mode feature which I am currently working on.

**Comment by alankritgupta091099** [comment]
Commits after this point "27a4db5" are for toggle dark mode feature which was one of the issues in the issues section which I solved.

**Comment by Anmolbansal1** [comment]
You need to submit a separate pull request regarding dark mode, please include only change mentioned in pull request. Try to not include more then one commit in a pull request.

**Comment by alankritgupta091099** [comment]
I am closing this pull request so as to open a fresh one.

**Pull request closed without merging**
