### PR TITLE
Fix test failing issue

### PR DESCRIPTION
**Pull request by carpecodeum**
Please provide enough information so that others can review your pull request:

Explain the **details** for making this change. What existing problem does the pull request solve?

The Travis-CI build was passing even though all the subsequent tests were failing.
So edited in the commands.py so that the build should pass (return 0) only if all the tests passed.
*Test plan (required)**
The travis build should now fail if the tests fail

**Closing issues** #514 

Put `closes #XXXX` in your comment and commit message to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by Anmolbansal1** [comment]
@carpecodeum I think you have referenced incorrect issue in this pull request, please fix it!!

**Comment by carpecodeum** [comment]
@Anmolbansal1 fixed it! Sure i will fix the tests also!

**Comment by Anmolbansal1** [comment]
@carpecodeum any update??

**Comment by carpecodeum** [comment]
@Anmolbansal1 I have been working on it but in between my midsems fell and thats why I couldnt work on it. I have resumed work on it!

**Comment by Anmolbansal1** [comment]
No problem :smile: but try to get it fixed at early because it will allow continuous integration of features in future without breaking project

**Comment by carpecodeum** [comment]
> No problem 😃 but try to get it fixed at early because it will allow continuous integration of features in future without breaking project

I think there is a directory import error this is making it harder to fix. I have tried alot still working on fixing it.

**Comment by carpecodeum** [comment]
> For now, let's merge this pr and I will create a new issue regarding fixing tests

Okay I will try to produce a pull request for that if i find a solution

**Pull request merged**
