### PR TITLE
Restructured and reformated project with eslint and standard js

### PR DESCRIPTION
**Pull request by Tushar19varshney**

### CODE REVIEW

**Comment by ivantha** [comment]
Closes #12

**Comment by ivantha** [comment]
p.s - It would've been much better if you could mention the issues separately or as points of the same issues and wait for the confirmation of the core contributors before making major changes to the whole code structure.

**Comment by Tushar19varshney** [comment]
> Hi @Tushar19varshney ,
> Thanks for the pull request! You've added some nice changes 
> I liked refactoring the routes into a separate index file. And it is a worthy addition to the project.
> 
> However adding double quotes instead of single quotes was an unnecessary change. Next time please make sure that the changes are requested/approved by the original authors of a project before making a pull request.

Actually i added .eslintrc , so there i mentioned double quotes instead of single.
Next time I'll be carefull !

**Comment by Tushar19varshney** [comment]
> p.s - It would've been much better if you could mention the issues separately or as points of the same issues and wait for the confirmation of the core contributors before making major changes to the whole code structure.

Next I'll be carefull!

**Comment by Tushar19varshney** [comment]
@ivantha I have reverted the double quotes into single quotes as you said.
Please review it!

**Comment by Tushar19varshney** [comment]
Should I resolve the conflicts ?

**Comment by Tushar19varshney** [comment]
I have squashed all my commits in one and changed the package.json as you said!

**Pull request merged**
