### PR TITLE
Add profile page & route

### PR DESCRIPTION
**Pull request by JosephSemrai**
Please provide enough information so that others can review your pull request:

Related to issue: #458 (Google Code-in Task)

- Add /profile route which renders the Profile component
- Add UserInfo component to be used in the profile page
- Create profile page

**Test plan (required)**

Tests succeed.
UI

**Code formatting**
Ran format script (prettier using the provided config)

**Closing issues**
Did not mention closing issue here as I am not 100% sure that this directly involves that issue.

### CODE REVIEW

**Comment by root5533** [comment]
@JosephSemrai there are few more codacy errors that needs to be fixed. After making changes please remove unnecessary commits by squashing them to one.

**Comment by JosephSemrai** [comment]
Hi, I made the above changes and rebased all of the commits into 'Add profile page and relevant components' https://github.com/scorelab/fact-Bounty/pull/461/commits/f29977febeed305360b37cf38383743d6085ca45

**Comment by Anmolbansal1** [comment]
@JosephSemrai looks good, just squash all commits in one

**Comment by JosephSemrai** [comment]
After a while, I had deleted the fork of the repository, and I'm unsure about how to perform the rebase as the repository is deleted. Should I create a separate pull request that takes its changes from an active repository with the rebased commits?

**Comment by Anmolbansal1** [comment]
@JosephSemrai yes go ahead..

**Comment by wdevon99** [comment]
@JosephSemrai Please squash all commits asap, thanks

**Comment by wdevon99** [comment]
@JosephSemrai Can you squash all commits

**Comment by JosephSemrai** [comment]
@wdevon99 
Unfortunately, I do not have access to the repository any longer as its id is "unknown".
image

I have duplicated the changes at #475, but I still have issues when rebasing the commits. Codacy does not detect extra line endings when I rebase the commits.

**Pull request closed without merging**
