### PR TITLE
fix material view

### PR DESCRIPTION
**Pull request by Danushka96**
Login and Registration View Fix

### CODE REVIEW

**Comment by root5533** [comment]
Let's make something simple and neat like example layout provided in [material-ui](https://material-ui.com/getting-started/page-layout-examples/) for sign in and register.

The source code link is given in [1].

[1][https://github.com/mui-org/material-ui/tree/master/docs/src/pages/getting-started/page-layout-examples/sign-in](https://github.com/mui-org/material-ui/tree/master/docs/src/pages/getting-started/page-layout-examples/sign-in)

**Comment by Danushka96** [comment]
@root5533 Fixed with Material View as given link!!

**Comment by Pradip-001** [comment]
@Danushka96 , @root5533 , are you working on login , register view? i would like to help, please let me know

**Comment by root5533** [comment]
@Pradip-001 this issue is almost resolved. Thank you for your support.

**Comment by Danushka96** [comment]
@root5533 I resolved the conflict on the first merge. Now I can't see any conflicts.

**Comment by Danushka96** [comment]
I updated my forked repo and local files with latest master version. Still can't see any conflicts...  Any Idea about the files that conflicted?

**Comment by Anmolbansal1** [comment]
You stacked that commit over your commit, when you will squash them you will see merge conflicts

**Comment by Anmolbansal1** [comment]
Also it will be better to move all styles to a new sass file in that folder.

**Pull request closed without merging**
