### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by ashu8912**
Corrected some grammer and spelling mistakes

### CODE REVIEW

**Comment by Pradip-001** [comment]
@ashu8912 , there are some other grammer mistakes as well in the same README file, please check them out and make necessary changes

**Comment by ivantha** [comment]
@ashu8912 Please rebase this.

**Comment by ivantha** [comment]
@ashu8912 Please fix the PR description too.

**Comment by ashu8912** [comment]
closing this will create another pull request to update readme 
the old commits somehow got deleted from my laptop

**Pull request closed without merging**
