### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by Anmolbansal1**
Fix general convention of routes in flask app
Fix route error in admin blueprint
Fix syntax error in app.py
Remove dev database from repository

### CODE REVIEW

**Comment by Anmolbansal1** [comment]
@wdevon99 kindly review..

**Comment by wdevon99** [comment]
> @wdevon99 kindly review..

Sorry for delay

**Comment by Anmolbansal1** [comment]
Codacy changes are not due to linting but some other and can't be fixed

**Comment by wdevon99** [comment]
> Codacy changes are not due to linting but some other and can't be fixed
> Also those errors are not new but due to old code

Ah alright

**Pull request merged**
