### PR TITLE
navbar responsive and dashboard message at center

### PR DESCRIPTION
**Pull request by Kanishka5**
Navbar is now  responsive:
A hamburger for navigation is added for mobile screens.

Dashboard message at centre of screen:
after login the welcome message is now visible at the centre of the screen.

### CODE REVIEW

**Comment by Kanishka5** [comment]
@root5533 please review the changes.

**Comment by root5533** [comment]
There are several issues in this PR. Please check @Kanishka5 

- Font size of navbar buttons in desktop view is too large.

- In mobile view, the top navbar should be shown with fact-bounty logo

- remove pink background color from mobile view of nav-links

- remove hamburger animation. It seems to fancy

**Comment by Kanishka5** [comment]
> There are several issues in this PR. Please check @Kanishka5
> 
> * Font size of navbar buttons in desktop view is too large.
> * In mobile view, the top navbar should be shown with fact-bounty logo
> * remove pink background color from mobile view of nav-links
> * remove hamburger animation. It seems to fancy

okay
working on it

**Comment by Kanishka5** [comment]
@root5533 I have made the required changes
Could you please review

**Comment by root5533** [comment]
- There should be a solid white background where the hamburger and logo resides. Also place an overlay when nav-links are displayed.

image

- Please revert the size of nav-link buttons in desktop view to original size. This is still too big

image

**Comment by Kanishka5** [comment]
> * There should be a solid white background where the hamburger and logo resides. Also place an overlay when nav-links are displayed.
> 
> image
> 
> * Please revert the size of nav-link buttons in desktop view to original size. This is still too big
> 
> image

okay
working on it

**Comment by Kanishka5** [comment]
@root5533 
made the changes.
Added white color to navbar.
factbounty2

factbounty_mob

**Comment by Kanishka5** [comment]
Added name validation
fixing issue #142
@root5533 could you please review

signup

**Comment by Kanishka5** [comment]
@root5533 @ivantha 
Please review

**Comment by root5533** [comment]
There are conflicts please resolve them @Kanishka5

**Comment by Kanishka5** [comment]
@root5533 @ivantha merge conflicts fixed

**Comment by ivantha** [comment]
@Kanishka5 I approved your PR. But still there are some conflicts. Please rebase so that we can get this merged 🙂

**Comment by Kanishka5** [comment]
@ivantha Thank you!
i will rebase it.

**Comment by Kanishka5** [comment]
@ivantha resolved conflicts and rebased

**Comment by Kanishka5** [comment]
Closes issue #125

**Pull request merged**
