### PR TITLE
Logout in navbar

### LINKED ISSUE #128: Logout button in navbar when logged in
# Expected Behavior

Logout should be displayed in navbar when user is logged in.

# Current Behavior

Currently when user is logged in, navbar stays static and shows login and sign up

### PR DESCRIPTION
**Pull request by sweezy793**
Logout option is now available in navbar when a user is logged in
Screenshot_20190307_221510

**Closing issues**
 Closes #128

### CODE REVIEW

**Comment by sweezy793** [comment]
@root5533 Please check this PR. Last PR had some merge conflicts. I did the changes you suggested.

**Comment by kartikpandey2** [comment]
@ivantha pull request [169](https://github.com/scorelab/fact-Bounty/pull/169) adds a logout button to navbar which has been merged. 😃

**Comment by sweezy793** [comment]
> Please fix the issues mentioned in the Codacy check and rebase

Done!

**Comment by root5533** [comment]
#169 fixed this issue

**Pull request closed without merging**
