### PR TITLE
Add twitter graph with sigma js

### PR DESCRIPTION
**Pull request by root5533**

### CODE REVIEW

**Comment by ivantha** [comment]
@root5533 Codacy is not passing. Most of these are false alerts. But there are some that you could fix.

**Comment by root5533** [comment]
@ivantha I will fix the code in TwitterGraph.jsx file but the rest of the files are actually from another open source project we are adapting. Will I require to make changes these as well ?

**Comment by ivantha** [comment]
> @ivantha I will fix the code in TwitterGraph.jsx file but the rest of the files are actually from another open source project we are adapting. Will I require to make changes these as well ?

If you are importing those files as a library or a git submodules it is okay to keep them as it is. However since we are taking individual files from another open source project, we have to make sure that they adhere to our coding standards.

**Comment by root5533** [comment]
> > @ivantha I will fix the code in TwitterGraph.jsx file but the rest of the files are actually from another open source project we are adapting. Will I require to make changes these as well ?
> 
> If you are importing those files as a library or a git submodules it is okay to keep them as it is. However since we are taking individual files from another open source project, we have to make sure that they adhere to our coding standards.

Understood. Ill look into them.

**Comment by root5533** [comment]
@ivantha please check and review

**Pull request merged**
