### PR TITLE
Add admin controller and a command to make admins 

### PR DESCRIPTION
**Pull request by carpecodeum**
Please provide enough information so that others can review your pull request:
Add admin controller and a command to make admins and allow only admins to access the stories/all route

Explain the **details** for making this change. What existing problem does the pull request solve?

This solves the issue of making admins for viewing and protecting certain routes like stories/all

**Test plan (required)**

Screenshot 2020-03-09 at 7 24 16 PM

Screenshot 2020-03-08 at 2 45 22 PM

**Closing issues** #470 

Put `closes #XXXX` in your comment and commit message to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by carpecodeum** [comment]
Sure @Anmolbansal1! Thanks for reviewing!

**Comment by Anmolbansal1** [comment]
Any update @carpecodeum , this pr is actually important for further changes so try to fix this like ASAP

**Comment by Anmolbansal1** [comment]
Just squash all commits and fix these minor codacy errors to maintain code standards :smiley:

**Comment by carpecodeum** [comment]
> Any update @carpecodeum , this pr is actually important for further changes so try to fix this like ASAP

Yes! I will fix them asap. Sorry for the delay.

**Comment by carpecodeum** [comment]
@Anmolbansal1 I think there is a problem with codacy. Its detecting errors even in the basic multi line commenting also in the way we initialise params in classmethod functions.This was happening before also, Please can you look into it and tell me if there is any problem from my side.

**Comment by carpecodeum** [comment]
@Anmolbansal1 I tried fixing this again its giving a warning. can you please look?

**Pull request merged**
