### PR TITLE
Added password hashing and compare as a part of user schema

### PR DESCRIPTION
**Pull request by Pradip-001**
Using schema middleware to hash password, also changed response status to 401 - Unauthorized for password incorrect, initially it was 400 - Bad Request

### CODE REVIEW

**Comment by Anmolbansal1** [comment]
@Pradip-001 please squash all your commits in one.
This is important while making a pull request.
You can refer to [this link](https://git-scm.com/docs/git-rebase#_interactive_mode) for help.

**Comment by Anmolbansal1** [comment]
Usually it is advisable to create a custom branch of issue and add a commit into it because otherwise you can't work further as you have to wait till your master branch get merged.

**Comment by Pradip-001** [comment]
for this issue , i think i have to create another PR or is there any other way , @Anmolbansal1 ?

**Comment by Anmolbansal1** [comment]
I think it would be better to create a new PR and make sure to create from custom branch

**Pull request closed without merging**
