### PR TITLE
Added password hashing and compare as a part of user schema

### PR DESCRIPTION
**Pull request by Pradip-001**
Added password hashing and compare logic in user schema

### CODE REVIEW

**Comment by Pradip-001** [comment]
Please review, @Anmolbansal1 , @ivantha

**Comment by ivantha** [comment]
@Pradip-001 Please rebase this 🙂

**Comment by Pradip-001** [comment]
@ivantha , please review , i have changed according to updated master also changed password incorrect status code

**Comment by Pradip-001** [comment]
@ivantha , @Anmolbansal1 please review the changes

**Pull request merged**
